### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by litghost** [plotly/jupyter-dash#70]
Is this project abandoned by plotly?  I have identified a couple issues and have fixes (e.g. #60), but there hasn't been any commits since January 22, 2021.  There also doesn't appear to have been any responses to issues.  I don't mind maintaining a fork with fixes, but would prefer to move good changes upstream if possible.

**Comment by fxheng** [comment]
I'm also interrested in getting this thing run for jupyterlab 3. Is plotly still there?

**Comment by nicolaskruchten** [comment]
Plotly is still here and this project isn't abandoned, it just mostly works without many modifications needed. I'm sorry we haven't been able to review your PR #60 yet @litghost :)

**Comment by litghost** [comment]
> Plotly is still here and this project isn't abandoned, it just mostly works without many modifications needed. I'm sorry we haven't been able to review your PR #60 yet @litghost :)

Since JupyterLab integrated async, I believe there are some issues with "infer_jupyter_config" that exist now.

I also have a fix for #63.

**Comment by litghost** [comment]
Ok.  I happen to have fixes for #62, #63 and #64, but after #60 didn't get any feedback one way or the other, I didn't create isolated PRs for those other fixes.  If fixes will be reviewed and merged, I'll start breaking out fixes and opening PRs.

**Comment by datainvestor** [comment]
#62 Is very serious issue, I wanted to introduce Dash in my company but so far I am failing to set even a working demo for them...

**Comment by litghost** [comment]
> #62 Is very serious issue, I wanted to introduce Dash in my company but so far I am failing to set even a working demo for them...

If you have time, I have proposed changes for #62 mixed in with #60 and some other changes in https://github.com/litghost/jupyter-dash/tree/iterate_jupyter_dash3 .  Feel free to take a look.

**Comment by fxheng** [comment]
Currently I'm using dash with only [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy)
2 main issues burden me: 
- First there is a issue while launching any flask server from the ipython and ipykernel stack. I think there is a double call somewhere always ending to block the choosen port. 
- Second is #62 preventing to get your session information.
Currently my workaround was a propers lab configuration to run the flask app from the terminal and use jupyter-server-proxy(You cannot use the console because of the port issue). This way you can take advantage of flask debugging session and and auto reload. Drawback is that your terminal is not link to the explorer and you need navigate and launch the python from shell command.

**Comment by t89** [comment]
Judging from the amount of issues and the current update schedule it might as well be dead.

**Comment by johnc1231** [comment]
Is there a current update schedule?

**Comment by cmosguy** [comment]
Sounds to me that they make the open source capabilities broken so  you are forced to buy their expensive enterprise solutions  👎🏽

**Comment by chriddyp** [comment]
Thanks everyone for sharing these issues and sorry for the radio silence on this issue.

We've merged 6 PRs in the last 30 days and 8 PRs since the start of the year. These versions are available in on `0.4.2` and `0.2.1`, see the CHANGELOG: https://github.com/plotly/jupyter-dash/blob/master/CHANGELOG.md

Closing this issue for now since we made recent activity and fixed those bugs. Please create new issues as you encounter problems.
